sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
before_script:
  - npm prune
script:
  - npm test
  - echo Unit tests passed, running end to end tests
  - npm run e2e
after_success:
  - npm run size
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
